### ISSUE TITLE
Following Godot's Style Guide

### ISSUE THREAD

**Issue by ghost** [bwhaines/dollar-shuffle#1]
Hey, I'm looking through the code and noticing that none of the code or file names follow the [style guide laid out in the Godot documentation.](https://docs.godotengine.org/en/3.0/getting_started/scripting/gdscript/gdscript_styleguide.html) Fixing that up would make it easier for other people who are familiar with Godot to get involved. It would also make the code look cleaner since the custom code would have the same style as the code built into the engine.

I could probably knock out a conversion for the current codebase in an afternoon and submit it as a pull request. @bwhaines lemme know if that's something you'd want.

**Comment by bwhaines** [comment]
I appreciate the offer, but it'll be good practice to go through and fix it myself.
